CUDA_VISIBLE_DEVICES=2 python inference_basic.py \
 --pretrained_model_name_or_path="./checkpoints/SVD/stable-video-diffusion-img2vid-xt" \
 --output_dir="./basic_infer/train_20250726" \
 --validation_control_folder="./inference/train/poses" \
 --validation_image="./inference/train/reference.png" \
 --width=576 \
 --height=1024 \
 --guidance_scale=3.0 \
 --num_inference_steps=25 \
 --posenet_model_name_or_path="./checkpoints/Animation/train_20250726/checkpoint-1800/pose_net-1800.pth" \
 --face_encoder_model_name_or_path="./checkpoints/Animation/train_20250726/checkpoint-1800/face_encoder-1800.pth" \
 --unet_model_name_or_path="./checkpoints/Animation/train_20250726/checkpoint-1800/unet-1800.pth" \
 --tile_size=16 \
 --overlap=4 \
 --noise_aug_strength=0.02 \
 --frames_overlap=4 \
 --decode_chunk_size=4 \
 --gradient_checkpointing